# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [2]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [3]:
'''

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = 
W = 
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)
'''
np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(3, 3, 3)
W = np.random.randn(3, 3, 3)
b = np.random.randn(1, 1, 1)

print("a_slice_prev=",a_slice_prev)
print("W=",W)
#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

a_slice_prev= [[[ 1.62434536 -0.61175641 -0.52817175]
  [-1.07296862  0.86540763 -2.3015387 ]
  [ 1.74481176 -0.7612069   0.3190391 ]]

 [[-0.24937038  1.46210794 -2.06014071]
  [-0.3224172  -0.38405435  1.13376944]
  [-1.09989127 -0.17242821 -0.87785842]]

 [[ 0.04221375  0.58281521 -1.10061918]
  [ 1.14472371  0.90159072  0.50249434]
  [ 0.90085595 -0.68372786 -0.12289023]]]
W= [[[-0.93576943 -0.26788808  0.53035547]
  [-0.69166075 -0.39675353 -0.6871727 ]
  [-0.84520564 -0.67124613 -0.0126646 ]]

 [[-1.11731035  0.2344157   1.65980218]
  [ 0.74204416 -0.19183555 -0.88762896]
  [-0.74715829  1.6924546   0.05080775]]

 [[-0.63699565  0.19091548  2.10025514]
  [ 0.12015895  0.61720311  0.30017032]
  [-0.35224985 -1.1425182  -0.34934272]]]
Z = -5.19283565556167
